/* eslint-disable */
/**
 * Generated API — re-generated by `npx convex dev`.
 *
 * THIS FILE IS AUTO-GENERATED. Do not edit manually.
 */

import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
