/* eslint-disable */
/**
 * Generated API types — re-generated by `npx convex dev`.
 *
 * THIS FILE IS AUTO-GENERATED. Do not edit manually.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as edits from "../edits.js";
import type * as exports from "../exports.js";
import type * as runs from "../runs.js";

declare const fullApi: ApiFromModules<{ edits: typeof edits; exports: typeof exports; runs: typeof runs }>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;
