/* eslint-disable */
/**
 * Generated data model types — re-generated by `npx convex dev`.
 *
 * THIS FILE IS AUTO-GENERATED. Do not edit manually.
 */

import type { DataModelFromSchemaDefinition } from "convex/server";
import type schema from "../schema.js";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
