/* eslint-disable */
/**
 * Generated API types — re-generated by `npx convex dev`.
 *
 * THIS FILE IS AUTO-GENERATED. Do not edit manually.
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as auth from "../auth.js";
import type * as edits from "../edits.js";
import type * as exports from "../exports.js";
import type * as http from "../http.js";
import type * as runs from "../runs.js";

declare const fullApi: ApiFromModules<{ auth: typeof auth; edits: typeof edits; exports: typeof exports; http: typeof http; runs: typeof runs }>;

export declare const api: FilterApi<typeof fullApi, FunctionReference<any, "public">>;
export declare const internal: FilterApi<typeof fullApi, FunctionReference<any, "internal">>;

export declare const components: {
  betterAuth: import("@convex-dev/better-auth/_generated/component.js").ComponentApi<"betterAuth">;
};
