/* eslint-disable */
/**
 * Generated server utilities — re-generated by `npx convex dev`.
 *
 * THIS FILE IS AUTO-GENERATED. Do not edit manually.
 */

import type { GenericDataModel } from "convex/server";
import type {
  MutationBuilder,
  QueryBuilder,
  ActionBuilder,
} from "convex/server";

export declare const query: QueryBuilder<GenericDataModel, "public">;
export declare const internalQuery: QueryBuilder<GenericDataModel, "internal">;
export declare const mutation: MutationBuilder<GenericDataModel, "public">;
export declare const internalMutation: MutationBuilder<GenericDataModel, "internal">;
export declare const action: ActionBuilder<GenericDataModel, "public">;
export declare const internalAction: ActionBuilder<GenericDataModel, "internal">;
