/* eslint-disable */
/**
 * Generated server utilities — re-generated by `npx convex dev`.
 *
 * THIS FILE IS AUTO-GENERATED. Do not edit manually.
 */

import {
  queryGeneric,
  mutationGeneric,
  actionGeneric,
} from "convex/server";

export const query = queryGeneric;
export const internalQuery = queryGeneric;
export const mutation = mutationGeneric;
export const internalMutation = mutationGeneric;
export const action = actionGeneric;
export const internalAction = actionGeneric;
